### ISSUE TITLE
Portland, Oregon

### ISSUE THREAD

**Issue by ramalam1** [teddywilson/defund12.org#21] opened 2020-06-04 18:21 UTC

**Comment by teddywilson** [comment] 2020-06-04 19:56
We are currently handling a lot of requests - please include the following information with your request:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Thank you!!

**Comment by tallfunnyjew** [comment] 2020-06-04 21:16
**Subject Message:** Defunding the Portland Police Department
**List of Emails:** mayorwheeler@portlandoregon.gov, Amanda@portlandoregon.gov, chloe@portlandoregon.gov, joann@portlandoregon.gov, AuditorHullCaballero@portlandoregon.gov, ipr@portlandoregon.gov, Ombudsman@portlandoregon.gov, ppbpio@portlandoregon.gov, sonia.schmanski@portlandoregon.gov
**Detailed Message:** file has been zipped & attached
[City of Portland.rtf.zip](https://github.com/teddywilson/defund12.org/files/4732760/City.of.Portland.rtf.zip)

**Comment by tallfunnyjew** [comment] 2020-06-04 21:17
Hopefully, that helps @teddywilson & @ramalam1  - if not, please advise.

**Comment by sporkbotic** [comment] 2020-06-04 21:17
cityinfo@portlandoregon.gov
 mayorwheeler@portlandoregon.gov
ppbpio@portlandoregon.gov
govrel@portlandoregon.gov
Tom.Rinehart@portlandoregon.gov
chloe@portlandoregon.gov
Amanda@portlandoregon.gov
oehr@portlandoregon.gov
markisha.smith@portlandoregon.gov

**Comment by lcl621** [comment] 2020-06-04 21:32
This is the related e-mail text I sent a couple days ago to:
cityinfo@portlandoregon.gov 
mayorwheeler@portlandoregon.gov
joann@portlandoregon.gov 
AuditorHullCaballero@portlandoregon.gov 

Subject: Disturbing Police Tactics

Body:

Hello Mayor Wheeler, Commissioner Hardesty, and Auditor Hull Caballero,

I am a Portland city resident living in SE (zip code: 97206). I have been following the recent protests against police brutality, and I am increasingly disturbed by the use of force by police in this city. There are plenty of videos showing police attacking citizens over the past few days, usually unprovoked and without discretion. Tonight, there was no curfew in place and yet still police used violent force in the name of "dispersing crowds". The constitution is very clear about the peoples' First Amendment rights to peacefully assemble.

I've linked to a few videos of PPB using terror tactics on citizens tonight:
https://twitter.com/matcha_chai/status/1268043556913987584
https://twitter.com/CAIROregon/status/1268039476938305536
https://twitter.com/alex_zee/status/1268047762848800768

Here's the PPB's reasoning for using chemical weapons on citizens: https://twitter.com/PortlandPolice/status/1268042456148271104

If I'm to understand -- the issue is that they were too close to a fence? So the police were authorized to use chemical weapons and 40mm bullets on citizens? It is increasingly clear that the most violent actors in our city are the police. If their terror tactics are the result of orders from the Chief and the Police Commissioner, then you both must step down immediately. If they are NOT acting under the direct orders of the Chief and the Commissioner, then you must investigate the actions of these officers.

The PPB's behaviors this weekend are offensive to me. Tonight is absolute proof that the police MUST be defunded and have their military-grade weapons taken away -- it is a danger to the citizens of Portland to allow police to continue using violent force and chemical weapons on the citizens of our city who are protesting that very same force. It is clear to me that the brutality the protesters are fighting against is alive and well in our city.

Police reform is not enough, and has proven time and time again to be ineffective at reducing police killings and brutality [https://www.theguardian.com/commentisfree/2020/may/31/the-answer-to-police-violence-is-not-reform-its-defunding-heres-why] . Body cams do not equal accountability and bias training does not reduce the number of Black people, Indigenous people, Latinx people and others disproportionately targeted by "law enforcement".  

If you want to "tackle crime", dedicate yourselves fully to ending poverty-- don't give the police force another 246.2 million to spend on riot gear, grenades, and chemical weapons to use against your city. 

Now is a chance for Portland to lead the country and show how demilitarization and defunding the police can create a safer city for all of us.  


Best Regards,

**Comment by Ceshion** [comment] 2020-06-04 23:09
I'm going to get started adding templates for these two emails now, I'll add a pull request for them shortly

**Comment by Ceshion** [comment] 2020-06-05 02:35
added in #76

**Comment by skullface** [comment] 2020-06-05 21:54
These two letters were merged in https://github.com/teddywilson/defund12.org/pull/76 ✨ with a follow-up for more email addresses in https://github.com/teddywilson/defund12.org/issues/85 💌, so this issue can be closed.

**Closed** 2020-06-06 01:41 UTC
Labels: meets issue requirements

**Comment by tallfunnyjew** [comment] 2020-06-08 19:54
Thanks for the great letter with video, @lcl621 - that's so important.
