### ISSUE TITLE
Add Honolulu, Hawaii!

### ISSUE THREAD

**Issue by lissah** [teddywilson/defund12.org#101] opened 2020-06-05 00:52 UTC
You can message me here or at my email address if you need help getting together the Honolulu official’s contact information. Please let me know if you need help!

**Comment by cstrouse** [comment] 2020-06-05 01:01
Duplicate of #89

**Comment by teddywilson** [comment] 2020-06-05 01:30
Closing, as it's a duplicate. Thanks @cstrouse !

**Closed by teddywilson** 2020-06-05 01:30 UTC
